openapi: 3.0.4
info:
  title: Airline Lookup
  description: >-
    Airline Lookup is a simple tool for getting information on airlines. It
    returns information on various airlines.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/airlinelookup:
    get:
      summary: Get Airline Info from IATA
      description: Get the airline information for a specific airline IATA code
      operationId: airlinelookup
      parameters:
        - name: iata
          in: query
          schema:
            type: string
          required: true
          description: >-
            The IATA code of the airline for which you want to get the
            information (e.g., AA)
          example: AA
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  - name: American Airlines
                    alias: null
                    iata: AA
                    icao: AAL
                    callsign: AMERICAN
                    country: United States
                    id: AA
                    islowcost: false
                    logourl: >-
                      https://storage.googleapis.com/apiverve/APIResources/arlinelookup/logos/AA.png?X-Goog-Algorithm=...
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
