name: apiverve_airlinelookup
description: Airline Lookup is a simple tool for getting information on airlines. It returns information on various airlines.
version: 1.1.13
homepage: https://apiverve.com/marketplace/airlinelookup?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/airlinelookup-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
